language: node_js
node_js:
 - "node"
services:
  - docker
before_install:
  - docker build -t igormcsouza/movie-review-plus-frontend .
script:
  - docker run igormcsouza/movie-review-plus-frontend npm run lint